// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8mFP6F2mQNPboFzuK_NP6RfLAkJATYmo',
    appId: '1:89409286432:web:8c47adc2d9442ca6922745',
    messagingSenderId: '89409286432',
    projectId: 'budget-manager-application',
    authDomain: 'budget-manager-application.firebaseapp.com',
    storageBucket: 'budget-manager-application.appspot.com',
    measurementId: 'G-CDZS6P3NK9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXhlddB52WekXas8Uf6zXeVUlg0nSuOuo',
    appId: '1:89409286432:android:79b77c28bcd4edef922745',
    messagingSenderId: '89409286432',
    projectId: 'budget-manager-application',
    storageBucket: 'budget-manager-application.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDP7v2tObrTll4dhGit-9NHVGrtSZcq60Y',
    appId: '1:89409286432:ios:8df2c5e176d2f0b9922745',
    messagingSenderId: '89409286432',
    projectId: 'budget-manager-application',
    storageBucket: 'budget-manager-application.appspot.com',
    iosBundleId: 'com.example.budgetManagerApplication',
  );
}
